;PROG0402
STSG	SEGMENT	STACK  'S'	;堆栈段
	DW	32  DUP(?)	;行2
STSG	ENDS
DATA	SEGMENT		;数据段
A	DW	123	;行5
B	DW	456	;行6
SUM	DW	?	;行7
DATA	ENDS
CODE	SEGMENT		;代码段
MAIN	PROC	FAR
	ASSUME	CS:CODE,DS:DATA,SS:STSG,ES:NOTHING
	MOV	AX,DATA	;与下条语句配合给DS赋值
	MOV	DS,AX
	MOV	AX,A	;行14
	ADD	AX,B	;行15
	MOV	SUM,AX	;行16
	MOV	AX,4C00H	;与下条语句配合返回操作系统
	INT	21H
MAIN	ENDP 
CODE	ENDS
	END	MAIN	;程序结束